import { Cloud, Code2, Gauge, Globe2, LineChart, LockKeyhole, MonitorCog, PanelsTopLeft, ShoppingBag, Wrench } from "lucide-react";

export const navigation=[{href:"/services",label:"Services"},{href:"/packages",label:"Packages"},{href:"/portfolio",label:"Work"},{href:"/process",label:"Process"},{href:"/about",label:"About"}];

export const services=[
{slug:"website-design-development",title:"Website Design & Development",short:"A professional, custom-built website that represents your business the way it deserves.",icon:PanelsTopLeft,audience:"New businesses, growing companies, professional services, and brands that need a stronger digital presence.",included:["Discovery and site strategy","Responsive UI/UX design","Development and testing","Contact and lead capture forms","Core SEO setup","Launch support and handover"],impact:"Build credibility, make the right first impression, and turn more visitors into genuine enquiries."},
{slug:"software-web-apps",title:"Software & Web Application Development",short:"Custom tools and systems built around how your business actually operates.",icon:Code2,audience:"Businesses with manual workflows, disconnected tools, internal admin needs, portals, dashboards, or bespoke customer experiences.",included:["Workflow discovery","System and data architecture","Responsive product UI","API and integration work","Role-based access","Testing, deployment, and support"],impact:"Replace repetitive admin and awkward workarounds with software designed for the way your team really works."},
{slug:"hosting-cloud-management",title:"Web Hosting & Cloud Management",short:"Fast, secure, reliable hosting, fully managed so you never have to think about it.",icon:Cloud,audience:"Businesses that want dependable hosting without managing servers, certificates, backups, or deployment details themselves.",included:["Managed hosting setup","SSL and domain configuration","Performance monitoring","Backups","Deployment support","Scaling guidance"],impact:"Keep your digital presence fast and available without making infrastructure another item on your to-do list."},
{slug:"maintenance-support",title:"Website Maintenance & Support",short:"Updates, backups, security monitoring, and small improvements handled quietly in the background.",icon:Wrench,audience:"Businesses that already have a site but need someone dependable to keep it healthy, current, and secure.",included:["Security and dependency updates","Uptime checks","Regular backups","Small content changes","Performance checks","Priority support options"],impact:"Reduce downtime, avoid neglected-site problems, and keep your website useful long after launch day."},
{slug:"growth-strategy",title:"Business Growth & Digital Strategy",short:"Ongoing guidance that turns your website into a working business asset instead of a static brochure.",icon:LineChart,audience:"Businesses that want an ongoing digital partner to help improve visibility, conversion, campaigns, and customer journeys.",included:["Monthly performance reviews","Conversion recommendations","Landing-page ideas","Content and campaign support","Analytics interpretation","Digital roadmap guidance"],impact:"Make better decisions about what to improve next, with one partner already familiar with your business and systems."},
{slug:"ecommerce",title:"E-commerce Development",short:"Online stores and transaction flows designed to be easy to manage and easy to buy from.",icon:ShoppingBag,audience:"Retailers, product businesses, subscription services, and teams that need dependable online sales infrastructure.",included:["Storefront design","Product and catalogue setup","Payment integration","Order workflows","Analytics","Launch and support"],impact:"Create a smoother path from browsing to payment, with the operational side built to stay manageable as sales grow."}
] as const;

export const packages=[
{name:"Starter",price:"R5,500",monthly:"R450/mo",bestFor:"New businesses needing a professional online presence.",highlight:false,features:["Up to 5 pages","Branded responsive design","Shared hosting included","Monthly check-in","Contact form","Basic SEO setup"]},
{name:"Growth",price:"R12,500",monthly:"R850/mo",bestFor:"Growing businesses that need more functionality and ongoing support.",highlight:true,features:["Up to 10 pages","Custom design","Managed cloud hosting","Bi-weekly updates and monitoring","Booking or e-commerce integration","Analytics and conversion support"]},
{name:"Enterprise",price:"From R25,000",monthly:"R1,500+/mo",bestFor:"Established businesses needing custom systems and full digital management.",highlight:false,features:["Custom scope","Full UX strategy","Scalable cloud infrastructure","Priority support","Custom software and integrations","Dedicated digital operations support"]}
] as const;

export const differentiators=[{icon:MonitorCog,title:"Ongoing support",text:"Real people keeping your site healthy, current, and useful after launch."},{icon:Gauge,title:"Growth-focused",text:"We look beyond launch day and keep improving the parts that affect real business outcomes."},{icon:LockKeyhole,title:"Managed properly",text:"Hosting, backups, security, monitoring, and maintenance stay under one roof."},{icon:Globe2,title:"One partner",text:"Design, development, infrastructure, support, and strategy without juggling multiple suppliers."}] as const;

export const faqs=[["How long does a website take to build?","Most Starter and Growth sites are completed within 2–4 weeks from approved design. Enterprise timelines depend on scope and integrations."],["Do I need to know anything technical?","No. You tell us about your business, customers, and goals. Sylvexa handles the technical decisions and explains anything you need to approve in plain language."],["What if I already have a website?","We can redesign, rebuild, improve, or migrate an existing site with as little disruption as possible."],["Who owns the website and domain?","You do. Sylvexa can manage them on your behalf, but the website and domain remain yours."],["What is included in maintenance?","Security updates, backups, uptime monitoring, health checks, and small content changes are included according to your support package."],["What happens if my site goes down?","Managed plans include uptime monitoring so problems can be identified and acted on quickly."],["Can you work with clients remotely?","Yes. Sylvexa is built to work with businesses remotely through clear calls, shared approvals, and transparent project communication."],["Can I upgrade later?","Absolutely. Packages are a starting point, not a cage. You can add services or move into a larger support plan as your business grows."]] as const;
export const processSteps=[["01","Discovery call","We learn about your business, goals, customers, and what is currently getting in the way.","1–2 days"],["02","Proposal & package","You get a clear scope, timeline, deliverables, and price before work starts.","1–2 days"],["03","Design","We create the structure and visual direction for approval before development gets expensive.","3–7 days"],["04","Development","We build, test, refine, and connect the pieces required for your project.","1–3 weeks"],["05","Launch","Your site goes live, hosting is configured, and we make sure the handover is clear.","1–2 days"],["06","Ongoing support","We stay on to maintain, monitor, improve, and help the digital side of your business keep moving.","Ongoing"]] as const;
