import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { FinalCta, MarketingLayout, PageHero, SectionIntro, styles } from "@/components/MarketingShell";
import { services } from "@/lib/marketing";

const serviceHeroVariants=["serviceA","serviceB","serviceC","serviceD","serviceE","serviceF"] as const;
const serviceHeroAccents=["make the first impression count","built around how you work","quiet infrastructure, steady days","keep it healthy after launch","small improvements compound","make buying feel easy"] as const;
export function generateStaticParams(){return services.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(item=>item.slug===slug);return service?{title:service.title,description:service.short}:{};}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const serviceIndex=services.findIndex(item=>item.slug===slug);const service=services[serviceIndex];if(!service){notFound();}const Icon=service.icon;const heroVariant=serviceHeroVariants[serviceIndex%serviceHeroVariants.length];const heroAccent=serviceHeroAccents[serviceIndex%serviceHeroAccents.length];return <MarketingLayout><PageHero variant={heroVariant} eyebrow="Sylvexa service" accent={heroAccent} title={service.title} body={service.short} primary="Request this service"/><section className={styles.section}><div className={styles.container}><div className={styles.grid2}><article className={styles.card}><div className={styles.cardIcon}><Icon size={24}/></div><h3>Who it is for</h3><p>{service.audience}</p></article><article className={styles.card}><h3>Why it matters</h3><p>{service.impact}</p></article></div></div></section><section className={styles.sectionAlt}><div className={styles.container}><SectionIntro eyebrow="Included" note="a sensible working scope" title="A clear scope, explained in plain language."/><div className={styles.grid3}>{service.included.map((item,index)=><article className={styles.card} key={item}><span className={styles.pill}>0{index+1}</span><h3>{item}</h3><p>Scoped around your actual project rather than padded with jargon or unnecessary extras.</p></article>)}</div><div className={styles.buttonRow}><Link className={styles.secondaryButton} href="/packages">See package options</Link><Link className={styles.primaryButton} href="/contact">Request this service <ArrowRight size={17}/></Link></div></div></section><FinalCta title={`Ready to talk about ${service.title.toLowerCase()}?`}/></MarketingLayout>}
