import Link from "next/link";
import { ArrowRight, Layers3, Mail, Menu, MessageCircle } from "lucide-react";
import { navigation } from "@/lib/marketing";
import styles from "./MarketingShell.module.css";
export { styles };

export function SiteHeader(){return <header className={styles.header}><div className={styles.navWrap}><Link href="/" className={styles.brand} aria-label="Sylvexa home"><span className={styles.brandMark}><Layers3 size={18}/></span><span>SYLVEXA</span></Link><nav className={styles.desktopNav} aria-label="Primary navigation">{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><div className={styles.navActions}><Link href="/contact" className={styles.navCta}>Start a project <ArrowRight size={15}/></Link><details className={styles.mobileMenu}><summary aria-label="Open navigation"><Menu size={20}/></summary><nav>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}<Link href="/contact">Contact</Link></nav></details></div></div></header>}
export function SiteFooter(){return <footer className={styles.footer}><div className={styles.footerGrid}><div><Link href="/" className={styles.brand}><span className={styles.brandMark}><Layers3 size={18}/></span><span>SYLVEXA</span></Link><p>Websites, software, hosting, support, and digital growth handled as one ongoing partnership.</p></div><div><strong>Explore</strong><Link href="/services">Services</Link><Link href="/packages">Packages</Link><Link href="/portfolio">Portfolio</Link><Link href="/about">About</Link></div><div><strong>Support</strong><Link href="/growth-support">Business Assistant</Link><Link href="/faq">FAQ</Link><Link href="/resources">Resources</Link><Link href="/contact">Contact</Link></div><div><strong>Contact</strong><a href="mailto:hello@sylvexa.com"><Mail size={14}/> hello@sylvexa.com</a><Link href="/contact"><MessageCircle size={14}/> Request a consultation</Link></div></div><div className={styles.footerBottom}><span>© {new Date().getFullYear()} Sylvexa. All rights reserved.</span><span>Built with the same care we promise clients.</span></div></footer>}
export function MarketingLayout({children}:{children:React.ReactNode}){return <><SiteHeader/><main className={styles.main}>{children}</main><SiteFooter/></>}
export function PageHero({eyebrow,title,body,primary="Start my project",primaryHref="/contact",secondary,secondaryHref="/packages"}:{eyebrow:string;title:string;body:string;primary?:string;primaryHref?:string;secondary?:string;secondaryHref?:string}){return <section className={styles.pageHero}><div className={styles.pageHeroGlow}/><span className={styles.eyebrow}>{eyebrow}</span><h1>{title}</h1><p>{body}</p><div className={styles.buttonRow}><Link className={styles.primaryButton} href={primaryHref}>{primary}<ArrowRight size={17}/></Link>{secondary&&<Link className={styles.secondaryButton} href={secondaryHref}>{secondary}</Link>}</div></section>}
export function SectionIntro({eyebrow,title,body,light=false}:{eyebrow:string;title:string;body?:string;light?:boolean}){return <div className={`${styles.sectionIntro} ${light?styles.lightText:""}`}><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2>{body&&<p>{body}</p>}</div>}
export function FinalCta({title="Ready for a website that works as hard as you do?",body="Let’s talk about what your business actually needs. No pressure, no jargon, just a clear next step."}:{title?:string;body?:string}){return <section className={styles.finalCta}><div><span className={styles.eyebrow}>Start here</span><h2>{title}</h2><p>{body}</p></div><Link className={styles.primaryButton} href="/contact">Start my project <ArrowRight size={17}/></Link></section>}
